import {z} from 'zod';
const text=z.string().trim().max(2000);const uuid=z.uuid();const optionalId=z.union([uuid,z.literal('')]).optional().transform(v=>v||undefined);
export const date=z.iso.date();
export const money=z.string().regex(/^\d{1,12}(\.\d{1,2})?$/,'Use a positive decimal amount with at most two decimal places');
export const customerSchema=z.object({name:text.min(2),name_en:text.optional(),type:text.min(1),phone:z.string().min(7).max(30),email:z.union([z.email(),z.literal('')]).optional(),area_id:uuid,representative_id:optionalId,classification:z.enum(['A','B','C','VIP']).default('B'),status:z.enum(['active','inactive','suspended','prospect']).default('active'),address:text.optional(),city:text.optional(),contact_person:text.optional(),whatsapp:text.optional(),latitude:z.coerce.number().min(-90).max(90).optional(),longitude:z.coerce.number().min(-180).max(180).optional(),credit_limit:money.optional(),tax_id:text.optional(),notes:text.optional(),details:z.record(z.string(),text).default({})});
const base={date,customer_id:optionalId,notes:text.optional(),status:z.enum(['draft','submitted']).default('submitted'),details:z.record(z.string(),text).default({})};
const customerRequired={...base,customer_id:uuid};
export const schemas={
 visits:z.object({...customerRequired,visit_type:text.min(1),purpose:text.min(1),outcome:text.optional(),next_action:text.optional(),follow_up:z.union([date,z.literal('')]).optional().transform(v=>v||undefined),check_in:z.iso.datetime().optional(),check_out:z.iso.datetime().optional(),latitude:z.coerce.number().min(-90).max(90).optional(),longitude:z.coerce.number().min(-180).max(180).optional()}),
 collections:z.object({...customerRequired,amount:money.refine(v=>BigInt(v.replace('.','').replace(/^0+/, '')||'0')>0),currency:z.string().regex(/^[A-Z]{3}$/).default('EGP'),payment_method:z.enum(['cash','cheque','bank_transfer','instapay','wallet','card','other']),reference:text.optional(),client_transaction_id:uuid}).superRefine((v,c)=>{if(v.payment_method==='cheque' && (!v.details.cheque_number||!v.details.bank||!v.details.due_date))c.addIssue({code:'custom',message:'Cheque number, bank and due date are required'});if(v.payment_method==='bank_transfer'&&(!v.reference||!v.details.bank))c.addIssue({code:'custom',message:'Bank and transfer reference are required'});}),
 invoices:z.object({...customerRequired,amount:money,currency:z.string().regex(/^[A-Z]{3}$/).default('EGP'),reference:text.min(1)}),
 plans:z.object({...base,area_id:uuid,title:text.min(2),plan_type:z.enum(['weekly','monthly','annual']),end_date:date,visit_target:z.coerce.number().int().min(0).max(10000),collection_target:money.default('0'),sales_target:money.default('0'),new_customer_target:z.coerce.number().int().min(0).max(10000).default(0),items:z.array(z.object({customer_id:uuid,date,activity:text.min(1)})).max(366).default([])}).refine(v=>v.end_date>=v.date,'End date must follow start date'),
 leaves:z.object({...base,leave_type_id:uuid,end_date:date}).refine(v=>v.end_date>=v.date && v.end_date.slice(0,4)===v.date.slice(0,4),'Dates must be ordered and in the same year')
};
export const userSchema=z.object({name:text.min(2),email:z.email(),password:z.string().min(12).max(128),phone:text.optional(),employee_code:text.optional(),role_id:uuid,area_ids:z.array(uuid).max(100),supervisor_id:optionalId});
