-- Generated relational module tables. Changes belong in a new migration after deployment.
CREATE TABLE visits (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies,customer_id uuid NOT NULL,representative_id uuid NOT NULL,area_id uuid,date date NOT NULL DEFAULT CURRENT_DATE,status text NOT NULL DEFAULT 'submitted' CHECK(status IN ('draft','submitted','reviewed','approved','rejected','confirmed','cancelled','completed')),notes text,details jsonb NOT NULL DEFAULT '{}',visit_type text NOT NULL DEFAULT 'routine',purpose text,outcome text,next_action text,follow_up date,check_in timestamptz,check_out timestamptz,latitude numeric(10,7),longitude numeric(10,7),CHECK(check_out IS NULL OR check_in IS NULL OR check_out>=check_in),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(company_id,id),FOREIGN KEY(company_id,customer_id) REFERENCES customers(company_id,id),FOREIGN KEY(company_id,representative_id) REFERENCES users(company_id,id),FOREIGN KEY(company_id,area_id) REFERENCES areas(company_id,id));
CREATE INDEX visits_rep_date_idx ON visits(company_id,representative_id,date);
CREATE INDEX visits_customer_date_idx ON visits(company_id,customer_id,date);
ALTER TABLE visits ENABLE ROW LEVEL SECURITY;
CREATE POLICY visits_read ON visits FOR SELECT USING(company_id=app_company() AND (app_scope('visits',representative_id,area_id) ));
CREATE POLICY visits_insert ON visits FOR INSERT WITH CHECK(company_id=app_company() AND representative_id=app_user() AND app_can('visits.create') AND (area_id IS NULL OR app_area(area_id)));
CREATE POLICY visits_update ON visits FOR UPDATE USING(company_id=app_company() AND ((representative_id=app_user() AND status='draft' AND app_can('visits.create')) OR (app_can('visits.approve') AND (area_id IS NULL OR app_area(area_id))))) WITH CHECK(company_id=app_company());
CREATE TABLE collections (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies,customer_id uuid NOT NULL,representative_id uuid NOT NULL,area_id uuid,date date NOT NULL DEFAULT CURRENT_DATE,status text NOT NULL DEFAULT 'submitted' CHECK(status IN ('draft','submitted','reviewed','approved','rejected','confirmed','cancelled','completed')),notes text,details jsonb NOT NULL DEFAULT '{}',amount numeric(16,2) NOT NULL CHECK(amount>0),currency text NOT NULL DEFAULT 'EGP',payment_method text NOT NULL CHECK(payment_method IN ('cash','cheque','bank_transfer','instapay','wallet','card','other')),reference text,client_transaction_id uuid NOT NULL,confirmed_by uuid,confirmed_at timestamptz,UNIQUE(company_id,client_transaction_id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(company_id,id),FOREIGN KEY(company_id,customer_id) REFERENCES customers(company_id,id),FOREIGN KEY(company_id,representative_id) REFERENCES users(company_id,id),FOREIGN KEY(company_id,area_id) REFERENCES areas(company_id,id));
CREATE INDEX collections_rep_date_idx ON collections(company_id,representative_id,date);
CREATE INDEX collections_customer_date_idx ON collections(company_id,customer_id,date);
ALTER TABLE collections ENABLE ROW LEVEL SECURITY;
CREATE POLICY collections_read ON collections FOR SELECT USING(company_id=app_company() AND (app_scope('collections',representative_id,area_id) ));
CREATE POLICY collections_insert ON collections FOR INSERT WITH CHECK(company_id=app_company() AND representative_id=app_user() AND app_can('collections.create') AND (area_id IS NULL OR app_area(area_id)));
CREATE POLICY collections_update ON collections FOR UPDATE USING(company_id=app_company() AND ((representative_id=app_user() AND status='draft' AND app_can('collections.create')) OR (app_can('collections.approve') AND (area_id IS NULL OR app_area(area_id))))) WITH CHECK(company_id=app_company());
CREATE TABLE invoices (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies,customer_id uuid NOT NULL,representative_id uuid NOT NULL,area_id uuid,date date NOT NULL DEFAULT CURRENT_DATE,status text NOT NULL DEFAULT 'submitted' CHECK(status IN ('draft','submitted','reviewed','approved','rejected','confirmed','cancelled','completed')),notes text,details jsonb NOT NULL DEFAULT '{}',amount numeric(16,2) NOT NULL CHECK(amount>=0),currency text NOT NULL DEFAULT 'EGP',reference text NOT NULL,UNIQUE(company_id,reference),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(company_id,id),FOREIGN KEY(company_id,customer_id) REFERENCES customers(company_id,id),FOREIGN KEY(company_id,representative_id) REFERENCES users(company_id,id),FOREIGN KEY(company_id,area_id) REFERENCES areas(company_id,id));
CREATE INDEX invoices_rep_date_idx ON invoices(company_id,representative_id,date);
CREATE INDEX invoices_customer_date_idx ON invoices(company_id,customer_id,date);
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY invoices_read ON invoices FOR SELECT USING(company_id=app_company() AND (app_scope('invoices',representative_id,area_id) OR (app_can('invoices.view_customer_history') AND app_area(area_id))));
CREATE POLICY invoices_insert ON invoices FOR INSERT WITH CHECK(company_id=app_company() AND representative_id=app_user() AND app_can('invoices.create') AND (area_id IS NULL OR app_area(area_id)));
CREATE POLICY invoices_update ON invoices FOR UPDATE USING(company_id=app_company() AND ((representative_id=app_user() AND status='draft' AND app_can('invoices.create')) OR (app_can('invoices.approve') AND (area_id IS NULL OR app_area(area_id))))) WITH CHECK(company_id=app_company());
CREATE TABLE plans (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies,customer_id uuid ,representative_id uuid NOT NULL,area_id uuid,date date NOT NULL DEFAULT CURRENT_DATE,status text NOT NULL DEFAULT 'submitted' CHECK(status IN ('draft','submitted','reviewed','approved','rejected','confirmed','cancelled','completed')),notes text,details jsonb NOT NULL DEFAULT '{}',title text NOT NULL,plan_type text NOT NULL CHECK(plan_type IN ('weekly','monthly','annual')),end_date date NOT NULL,visit_target int NOT NULL DEFAULT 0 CHECK(visit_target>=0),collection_target numeric(16,2) NOT NULL DEFAULT 0 CHECK(collection_target>=0),sales_target numeric(16,2) NOT NULL DEFAULT 0 CHECK(sales_target>=0),new_customer_target int NOT NULL DEFAULT 0 CHECK(new_customer_target>=0),CHECK(end_date>=date),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(company_id,id),FOREIGN KEY(company_id,customer_id) REFERENCES customers(company_id,id),FOREIGN KEY(company_id,representative_id) REFERENCES users(company_id,id),FOREIGN KEY(company_id,area_id) REFERENCES areas(company_id,id));
CREATE INDEX plans_rep_date_idx ON plans(company_id,representative_id,date);
CREATE INDEX plans_customer_date_idx ON plans(company_id,customer_id,date);
ALTER TABLE plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY plans_read ON plans FOR SELECT USING(company_id=app_company() AND (app_scope('plans',representative_id,area_id) ));
CREATE POLICY plans_insert ON plans FOR INSERT WITH CHECK(company_id=app_company() AND representative_id=app_user() AND app_can('plans.create') AND (area_id IS NULL OR app_area(area_id)));
CREATE POLICY plans_update ON plans FOR UPDATE USING(company_id=app_company() AND ((representative_id=app_user() AND status='draft' AND app_can('plans.create')) OR (app_can('plans.approve') AND (area_id IS NULL OR app_area(area_id))))) WITH CHECK(company_id=app_company());
CREATE TABLE leaves (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies,customer_id uuid ,representative_id uuid NOT NULL,area_id uuid,date date NOT NULL DEFAULT CURRENT_DATE,status text NOT NULL DEFAULT 'submitted' CHECK(status IN ('draft','submitted','reviewed','approved','rejected','confirmed','cancelled','completed')),notes text,details jsonb NOT NULL DEFAULT '{}',leave_type_id uuid NOT NULL, end_date date NOT NULL,days numeric(6,2) NOT NULL CHECK(days>0),FOREIGN KEY(company_id,leave_type_id) REFERENCES leave_types(company_id,id),CHECK(end_date>=date),CHECK(extract(year from date)=extract(year from end_date)),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(company_id,id),FOREIGN KEY(company_id,customer_id) REFERENCES customers(company_id,id),FOREIGN KEY(company_id,representative_id) REFERENCES users(company_id,id),FOREIGN KEY(company_id,area_id) REFERENCES areas(company_id,id));
CREATE INDEX leaves_rep_date_idx ON leaves(company_id,representative_id,date);
CREATE INDEX leaves_customer_date_idx ON leaves(company_id,customer_id,date);
ALTER TABLE leaves ENABLE ROW LEVEL SECURITY;
CREATE POLICY leaves_read ON leaves FOR SELECT USING(company_id=app_company() AND (app_scope('leaves',representative_id,area_id) ));
CREATE POLICY leaves_insert ON leaves FOR INSERT WITH CHECK(company_id=app_company() AND representative_id=app_user() AND app_can('leaves.create') AND (area_id IS NULL OR app_area(area_id)));
CREATE POLICY leaves_update ON leaves FOR UPDATE USING(company_id=app_company() AND ((representative_id=app_user() AND status='draft' AND app_can('leaves.create')) OR (app_can('leaves.approve') AND (area_id IS NULL OR app_area(area_id))))) WITH CHECK(company_id=app_company());
CREATE TABLE plan_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL,plan_id uuid NOT NULL,customer_id uuid NOT NULL,date date NOT NULL,activity text NOT NULL,FOREIGN KEY(company_id,plan_id) REFERENCES plans(company_id,id),FOREIGN KEY(company_id,customer_id) REFERENCES customers(company_id,id));
ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
CREATE POLICY companies_read ON companies FOR SELECT USING(id=app_company() AND (true));
CREATE POLICY companies_write ON companies FOR ALL USING(id=app_company() AND (app_can('settings.manage'))) WITH CHECK(id=app_company() AND (app_can('settings.manage')));
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
CREATE POLICY users_read ON users FOR SELECT USING(company_id=app_company() AND (id=app_user() OR app_can('users.view') OR EXISTS(SELECT 1 FROM user_areas ua WHERE ua.user_id=users.id AND app_area(ua.area_id))));
CREATE POLICY users_write ON users FOR ALL USING(company_id=app_company() AND (app_can('users.edit'))) WITH CHECK(company_id=app_company() AND (app_can('users.edit')));
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY roles_read ON roles FOR SELECT USING(company_id=app_company() AND (true));
CREATE POLICY roles_write ON roles FOR ALL USING(company_id=app_company() AND (app_can('roles.manage'))) WITH CHECK(company_id=app_company() AND (app_can('roles.manage')));
ALTER TABLE regions ENABLE ROW LEVEL SECURITY;
CREATE POLICY regions_read ON regions FOR SELECT USING(company_id=app_company() AND (true));
CREATE POLICY regions_write ON regions FOR ALL USING(company_id=app_company() AND (app_can('areas.manage'))) WITH CHECK(company_id=app_company() AND (app_can('areas.manage')));
ALTER TABLE areas ENABLE ROW LEVEL SECURITY;
CREATE POLICY areas_read ON areas FOR SELECT USING(company_id=app_company() AND (app_area(id) OR app_can('areas.manage')));
CREATE POLICY areas_write ON areas FOR ALL USING(company_id=app_company() AND (app_can('areas.manage'))) WITH CHECK(company_id=app_company() AND (app_can('areas.manage')));
ALTER TABLE teams ENABLE ROW LEVEL SECURITY;
CREATE POLICY teams_read ON teams FOR SELECT USING(company_id=app_company() AND (true));
CREATE POLICY teams_write ON teams FOR ALL USING(company_id=app_company() AND (app_can('areas.manage'))) WITH CHECK(company_id=app_company() AND (app_can('areas.manage')));
ALTER TABLE user_areas ENABLE ROW LEVEL SECURITY;
CREATE POLICY user_areas_read ON user_areas FOR SELECT USING(company_id=app_company() AND (user_id=app_user() OR app_can('users.view') OR app_area(area_id)));
CREATE POLICY user_areas_write ON user_areas FOR ALL USING(company_id=app_company() AND (app_can('users.edit'))) WITH CHECK(company_id=app_company() AND (app_can('users.edit')));
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY user_roles_read ON user_roles FOR SELECT USING(company_id=app_company() AND (true));
CREATE POLICY user_roles_write ON user_roles FOR ALL USING(company_id=app_company() AND (app_can('roles.manage'))) WITH CHECK(company_id=app_company() AND (app_can('roles.manage')));
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY customers_read ON customers FOR SELECT USING(company_id=app_company() AND (deleted_at IS NULL AND app_area(area_id) AND app_can('customers.view')));
CREATE POLICY customers_write ON customers FOR ALL USING(company_id=app_company() AND (app_area(area_id) AND app_can('customers.edit'))) WITH CHECK(company_id=app_company() AND (app_area(area_id) AND app_can('customers.edit')));
ALTER TABLE customer_assignments ENABLE ROW LEVEL SECURITY;
CREATE POLICY customer_assignments_read ON customer_assignments FOR SELECT USING(company_id=app_company() AND (EXISTS(SELECT 1 FROM customers c WHERE c.id=customer_id)));
CREATE POLICY customer_assignments_write ON customer_assignments FOR ALL USING(company_id=app_company() AND (app_can('customers.edit'))) WITH CHECK(company_id=app_company() AND (app_can('customers.edit')));
ALTER TABLE leave_types ENABLE ROW LEVEL SECURITY;
CREATE POLICY leave_types_read ON leave_types FOR SELECT USING(company_id=app_company() AND (true));
CREATE POLICY leave_types_write ON leave_types FOR ALL USING(company_id=app_company() AND (app_can('settings.manage'))) WITH CHECK(company_id=app_company() AND (app_can('settings.manage')));
ALTER TABLE leave_balances ENABLE ROW LEVEL SECURITY;
CREATE POLICY leave_balances_read ON leave_balances FOR SELECT USING(company_id=app_company() AND (user_id=app_user() OR app_can('leaves.manage_balance') OR app_can('leaves.approve')));
CREATE POLICY leave_balances_write ON leave_balances FOR ALL USING(company_id=app_company() AND (app_can('leaves.manage_balance') OR app_can('leaves.approve'))) WITH CHECK(company_id=app_company() AND (app_can('leaves.manage_balance') OR app_can('leaves.approve')));
ALTER TABLE approval_workflows ENABLE ROW LEVEL SECURITY;
CREATE POLICY approval_workflows_read ON approval_workflows FOR SELECT USING(company_id=app_company() AND (true));
CREATE POLICY approval_workflows_write ON approval_workflows FOR ALL USING(company_id=app_company() AND (app_can('settings.manage'))) WITH CHECK(company_id=app_company() AND (app_can('settings.manage')));
ALTER TABLE approval_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY approval_requests_read ON approval_requests FOR SELECT USING(company_id=app_company() AND (submitted_by=app_user() OR (app_can(module||'.approve') AND (area_id IS NULL OR app_area(area_id)))));
CREATE POLICY approval_requests_write ON approval_requests FOR ALL USING(company_id=app_company() AND (submitted_by=app_user() OR (app_can(module||'.approve') AND (area_id IS NULL OR app_area(area_id))))) WITH CHECK(company_id=app_company() AND (submitted_by=app_user() OR (app_can(module||'.approve') AND (area_id IS NULL OR app_area(area_id)))));
ALTER TABLE approval_actions ENABLE ROW LEVEL SECURITY;
CREATE POLICY approval_actions_read ON approval_actions FOR SELECT USING(company_id=app_company() AND (EXISTS(SELECT 1 FROM approval_requests r WHERE r.id=request_id)));
CREATE POLICY approval_actions_write ON approval_actions FOR ALL USING(company_id=app_company() AND (approver_id=app_user() AND EXISTS(SELECT 1 FROM approval_requests r WHERE r.id=request_id AND app_can(r.module||'.approve')))) WITH CHECK(company_id=app_company() AND (approver_id=app_user() AND EXISTS(SELECT 1 FROM approval_requests r WHERE r.id=request_id AND app_can(r.module||'.approve'))));
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY notifications_read ON notifications FOR SELECT USING(company_id=app_company() AND (user_id=app_user()));
CREATE POLICY notifications_write ON notifications FOR ALL USING(company_id=app_company() AND (user_id=app_user())) WITH CHECK(company_id=app_company() AND (user_id=app_user()));
ALTER TABLE attachments ENABLE ROW LEVEL SECURITY;
CREATE POLICY attachments_read ON attachments FOR SELECT USING(company_id=app_company() AND (uploaded_by=app_user() OR app_can('customers.view')));
CREATE POLICY attachments_write ON attachments FOR ALL USING(company_id=app_company() AND (uploaded_by=app_user())) WITH CHECK(company_id=app_company() AND (uploaded_by=app_user()));
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY audit_logs_read ON audit_logs FOR SELECT USING(company_id=app_company() AND (app_can('audit.view')));
CREATE POLICY audit_logs_write ON audit_logs FOR ALL USING(company_id=app_company() AND (false)) WITH CHECK(company_id=app_company() AND (false));
ALTER TABLE plan_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY plan_items_read ON plan_items FOR SELECT USING(company_id=app_company() AND (EXISTS(SELECT 1 FROM plans p WHERE p.id=plan_id)));
CREATE POLICY plan_items_write ON plan_items FOR ALL USING(company_id=app_company() AND (EXISTS(SELECT 1 FROM plans p WHERE p.id=plan_id AND p.representative_id=app_user() AND p.status IN ('draft','submitted')))) WITH CHECK(company_id=app_company() AND (EXISTS(SELECT 1 FROM plans p WHERE p.id=plan_id AND p.representative_id=app_user() AND p.status IN ('draft','submitted'))));
CREATE POLICY customers_create ON customers FOR INSERT WITH CHECK(company_id=app_company() AND created_by=app_user() AND app_area(area_id) AND app_can('customers.create'));
CREATE POLICY audit_insert ON audit_logs FOR INSERT WITH CHECK(company_id=app_company() AND user_id=app_user());
CREATE POLICY notification_insert ON notifications FOR INSERT WITH CHECK(company_id=app_company());
GRANT USAGE ON SCHEMA public TO fieldforce_app;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO fieldforce_app;
REVOKE ALL ON sessions,password_resets,login_attempts FROM fieldforce_app;
REVOKE INSERT,UPDATE,DELETE ON permissions,role_permissions FROM fieldforce_app;
REVOKE UPDATE,DELETE ON audit_logs,approval_actions,customer_assignments FROM fieldforce_app;
